package com.css.form;

import com.css.dao.ViewProduct;
import com.css.dao.ViewProfile;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raju
 */
public class Admin extends javax.swing.JFrame {


    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Manager = new javax.swing.JButton();
        customer = new javax.swing.JButton();
        Mp = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ManageCourierbtn = new javax.swing.JButton();
        CompletedCourierbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Admin Profile.");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Minion Pro SmBd", 3, 24)); // NOI18N
        jLabel1.setText("Welcome! To Admin Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 388, -1));

        Manager.setFont(new java.awt.Font("Trajan Pro", 2, 14)); // NOI18N
        Manager.setText("Manage Profiles");
        Manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerActionPerformed(evt);
            }
        });
        getContentPane().add(Manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        customer.setFont(new java.awt.Font("Trajan Pro", 2, 14)); // NOI18N
        customer.setText("Manage Product");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        getContentPane().add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        Mp.setFont(new java.awt.Font("Trajan Pro", 2, 14)); // NOI18N
        Mp.setText("View report");
        Mp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MpMouseClicked(evt);
            }
        });
        Mp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpActionPerformed(evt);
            }
        });
        getContentPane().add(Mp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 151, -1));

        jButton4.setFont(new java.awt.Font("Trajan Pro", 2, 14)); // NOI18N
        jButton4.setText("View Products");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 171, -1));

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 133, 36));

        jButton1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jButton1.setText("Order Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 68, 172, -1));

        jButton3.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jButton3.setText("Recent Request Account");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Manage Order");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 123, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Manage Users");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 138, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Manage Report");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Manage Delivery");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Manage Feedback");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        ManageCourierbtn.setFont(new java.awt.Font("Trajan Pro", 2, 14)); // NOI18N
        ManageCourierbtn.setText("Manage courier");
        ManageCourierbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageCourierbtnMouseClicked(evt);
            }
        });
        ManageCourierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCourierbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ManageCourierbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        CompletedCourierbtn.setFont(new java.awt.Font("Trajan Pro", 2, 14)); // NOI18N
        CompletedCourierbtn.setText("completed courier");
        CompletedCourierbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompletedCourierbtnMouseClicked(evt);
            }
        });
        CompletedCourierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompletedCourierbtnActionPerformed(evt);
            }
        });
        getContentPane().add(CompletedCourierbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jButton2.setFont(new java.awt.Font("Trajan Pro", 2, 14)); // NOI18N
        jButton2.setText("View Feedback");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/css/form/java pic/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerActionPerformed
        this.setVisible(false);
        AdminProfiles ac = new AdminProfiles();
        ac.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_ManagerActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        this.setVisible(false);
        AdminProducts ap = new AdminProducts();
        ap.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void MpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpActionPerformed
 // TODO add your handling code here:
    }//GEN-LAST:event_MpActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                setVisible(false);
                LoginPage log = new LoginPage();
                log.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                setVisible(false);
                ViewProduct log = new ViewProduct();
                log.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                setVisible(false);
                AdminManageOrder log = new AdminManageOrder();
                log.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MpMouseClicked
        this.setVisible(false);
        ViewProfile ap = new ViewProfile();
        ap.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_MpMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        setVisible(false);
        AdminAccount a = new AdminAccount();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void CompletedCourierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompletedCourierbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompletedCourierbtnActionPerformed

    private void ManageCourierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCourierbtnActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_ManageCourierbtnActionPerformed

    private void ManageCourierbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCourierbtnMouseClicked
             setVisible(false);
             AdminManageCourier p;
        p = new AdminManageCourier();
             p.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_ManageCourierbtnMouseClicked

    private void CompletedCourierbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompletedCourierbtnMouseClicked

setVisible(false);
AdminViewCompletedCourier cc=new AdminViewCompletedCourier();
cc.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_CompletedCourierbtnMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    this.setVisible(false);
    FeedbackTable fd=new FeedbackTable();
    fd.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompletedCourierbtn;
    private javax.swing.JButton ManageCourierbtn;
    private javax.swing.JButton Manager;
    private javax.swing.JButton Mp;
    private javax.swing.JButton customer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
