/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.css.form;

import com.css.bll.PendingCourier;
import com.css.dao.PendingCourierDao;
import com.css.dao.PendingCourierDaoImpl;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Raju
 */
public class AdminManageCourier extends javax.swing.JFrame {

    /**
     * Creates new form PendingOrders
     */
    public AdminManageCourier() {
        initComponents();
        loadData();
        
      
    }
    private void loadData() {
        try {
            ArrayList<String> dataList;
            PendingCourierDaoImpl pcd = new PendingCourierDaoImpl();
            dataList = pcd.getAllCourier();
            DefaultTableModel dtm = new DefaultTableModel(new String[]{"ParcelNo", "CustomerName", "CustomerPhone",
                "DeliveryDate","Product","Destination","Status"}, 0);
            Object[] tableLines = dataList.toArray();
            for (Object tableLine : tableLines) {
                String lines = tableLine.toString();
                String[] row = lines.split(",");
                dtm.addRow(row);
            }
            PendingCouriertable.setModel(dtm);

        } catch (IOException ex) {
        }
    }
    
        
private void showPendingCouriertable()
    {
        BufferedReader br = null;
        try {
            String filePath = "PeindingCourier.txt";
            File file = new File(filePath);
            DefaultTableModel model = (DefaultTableModel) PendingCouriertable.getModel();
            br = new BufferedReader(new FileReader(file));            
            Object[] tableLines = br.lines().toArray();
            for (Object tableLine : tableLines) {
                String line = tableLine.toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminManageCourier.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(AdminManageCourier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PendingCouriertable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtParcelNo = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        txtCustPH = new javax.swing.JTextField();
        txtDeliDate = new javax.swing.JTextField();
        txtProduct = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        set = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pending Courier");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 11, -1, -1));

        PendingCouriertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parcel No.", "Customer Name", "Cust PH", "Delivery Date", "Product", "Destination", "Status"
            }
        ));
        PendingCouriertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingCouriertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PendingCouriertable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 43, 691, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Parcel No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 108, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Customer Phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 139, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Delivery Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 177, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Product");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 215, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Destination");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 253, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 291, 70, -1));
        getContentPane().add(txtParcelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 133, -1));
        getContentPane().add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 133, -1));
        getContentPane().add(txtCustPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 133, -1));
        getContentPane().add(txtDeliDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 133, -1));

        txtProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 133, -1));

        txtDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinationActionPerformed(evt);
            }
        });
        getContentPane().add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 133, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Progress", "Picked UP", "Delivered" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 133, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 345, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("Go Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 466, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete Selected Item");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 484, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 345, -1, -1));

        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });
        getContentPane().add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 485, 97, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/css/form/java pic/java1Background.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -20, 1190, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductActionPerformed

    private void txtDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinationActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
setVisible(false);
Admin a=new Admin();
a.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
                                  // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void PendingCouriertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingCouriertableMouseClicked
     DefaultTableModel tab = (DefaultTableModel) PendingCouriertable.getModel();
        int selectedRowIndex = PendingCouriertable.getSelectedRow();
        txtParcelNo.setText(tab.getValueAt(selectedRowIndex, 0).toString());
        txtCustName.setText(tab.getValueAt(selectedRowIndex, 1).toString());
        txtCustPH.setText(tab.getValueAt(selectedRowIndex, 2).toString()); 
        txtDeliDate.setText(tab.getValueAt(selectedRowIndex, 3).toString());  
        txtProduct.setText(tab.getValueAt(selectedRowIndex, 4).toString());  
        txtDestination.setText(tab.getValueAt(selectedRowIndex, 5).toString());  
// TODO add your handling code here:
    }//GEN-LAST:event_PendingCouriertableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      
        set.setText("");
          DefaultTableModel tab =(DefaultTableModel)PendingCouriertable.getModel();
       if(PendingCouriertable.getSelectedRow() == -1)
       {
           if(PendingCouriertable.getRowCount() == 0)
           {
               set.setText("Table is Empty");
           }else{
               set.setText("You must Select a Manager");
           }
           }else{
           tab.setValueAt(txtParcelNo.getText(), PendingCouriertable.getSelectedRow(), 0);
           tab.setValueAt(txtCustName.getText(), PendingCouriertable.getSelectedRow(), 1);
           tab.setValueAt(txtCustPH.getText(), PendingCouriertable.getSelectedRow(), 2);
           tab.setValueAt(txtDeliDate.getText(),PendingCouriertable.getSelectedRow(),3);
           tab.setValueAt(txtProduct.getText(),PendingCouriertable.getSelectedRow(),4);
           tab.setValueAt(txtDestination.getText(),PendingCouriertable.getSelectedRow(),5);
           tab.setValueAt(cmbStatus.getSelectedItem().toString(), PendingCouriertable.getSelectedRow(), 6);
           
           PendingCourierDao pcd = new PendingCourierDaoImpl();
           PendingCourier pc= new PendingCourier();
           pc.Update(txtParcelNo.getText(),txtCustName.getText(),txtCustPH.getText(),
          txtDeliDate.getText(),txtProduct.getText(),txtDestination.getText(),cmbStatus.getSelectedItem().toString());  
                    
       } 
       

// TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
  
      PendingCourierDao pcd = new PendingCourierDaoImpl();
        PendingCourier pc = new PendingCourier();

        
        pc.setParcelno(txtParcelNo.getText());
        pc.setCustomerName(txtCustName.getText());
        pc.setCustomerPhone(txtCustPH.getText());
        pc.setDeliveryDate(txtDeliDate.getText());
        pc.setProduct(txtProduct.getText());
        pc.setDestination(txtDestination.getText());
        pc.setStatus(cmbStatus.getSelectedItem().toString());
        

 
            // TODO add your handling code here:
          set.setText("");
        DefaultTableModel dtm =(DefaultTableModel)PendingCouriertable.getModel();
       
       if(!txtParcelNo.getText().trim().equals("") && !txtCustName.getText().trim().equals("") && !txtCustPH.getText().trim().equals("") && 
               !txtDeliDate.getText().trim().equals("")&& !txtProduct.getText().trim().equals("")&& !txtDestination.getText().trim().equals("")
               && !cmbStatus.getSelectedItem().toString().equals("")){
           
         JOptionPane.showMessageDialog(null, "Courier Register Successfull."); 
           try {
            pcd.SaveCourier(pc);
            dtm.addRow(new Object[]{txtParcelNo.getText(),txtCustName.getText(), txtCustPH.getText(), txtDeliDate.getText(),
            txtProduct.getText(),txtDestination.getText(),cmbStatus});
        } catch (IOException ex) {
            Logger.getLogger(AdminProfiles.class.getName()).log(Level.SEVERE, null, ex);
        }   

     
       }else{
        set.setText("Sorry! Please fill all the blank. Thank You!!!!");
       }     // TODO add your handling code here:
    }                                         

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        DefaultTableModel model =(DefaultTableModel)PendingCouriertable.getModel();
           if(PendingCouriertable.getSelectedRow() == -1)
       {
           if(PendingCouriertable.getRowCount() == 0)
           {
               set.setText("Table is Empty");
           }else{
               set.setText("You must Select a Name of Student");
           }
       }else{
            try {
                model.removeRow(PendingCouriertable.getSelectedRow());
                PendingCourierDaoImpl pcd= new PendingCourierDaoImpl();
                pcd.deleteCourier(txtParcelNo.getText());
                pcd.deleteCourier(txtCustName.getText());
                pcd.deleteCourier(txtCustPH.getText());
                pcd.deleteCourier(txtDeliDate.getText());
                pcd.deleteCourier(txtProduct.getText());
                pcd.deleteCourier(txtDestination.getText());
                pcd.deleteCourier(cmbStatus.getSelectedItem().toString());
                
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Courier deleted succesfully");
                Logger.getLogger(AdminManageCourier.class.getName()).log(Level.SEVERE, null, ex);
            }
       }    
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtParcelNo.setText("");
        txtCustName.setText("");
        txtCustPH.setText("");
        txtDeliDate.setText("");     
        txtProduct.setText("");

        txtDestination.setText("");
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setActionPerformed
/*
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed
*/
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

      
    
     private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {                                      
               // TODO add your handling code here:
    }                                     

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      
   
// TODO add your handling code here:
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageCourier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageCourier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageCourier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageCourier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminManageCourier().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PendingCouriertable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField set;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustPH;
    private javax.swing.JTextField txtDeliDate;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtParcelNo;
    private javax.swing.JTextField txtProduct;
    // End of variables declaration//GEN-END:variables
}
