package com.css.form;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.css.bll.Profile;
import com.css.dao.ProfileDao;
import com.css.dao.ProfileDaoImpl;
import com.css.dao.ViewProfile;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raju
 */
public class AdminProfiles extends javax.swing.JFrame {

    /**
     * Creates new form AdminCustomer
     */
    public AdminProfiles() {
        initComponents();
        loadData();
        showRecenttable();
    }
    private void loadData() {
        try {
            ArrayList<String> dataList;
            ProfileDaoImpl sdi = new ProfileDaoImpl();
            dataList = sdi.getAllProfiles();
            DefaultTableModel dtm = new DefaultTableModel(new String[]{"Product ID", "Name", "Price", "Type"}, 0);
            Object[] tableLines = dataList.toArray();
            for (Object tableLine : tableLines) {
                String lines = tableLine.toString();
                String[] row = lines.split(",");
                dtm.addRow(row);
            }
            ProfileTable.setModel(dtm);

        } catch (IOException ex) {
        }
    }
private void showRecenttable()
    {
        String filePath = "Request.txt";
        File file = new File(filePath);
        
        DefaultTableModel model = (DefaultTableModel) RecentTable.getModel();
                try{
            BufferedReader br = new BufferedReader(new FileReader(file));            
            Object[] tableLines = br.lines().toArray();
            for (Object tableLine : tableLines) {
                String line = tableLine.toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }
        }catch (IOException ex){
            Logger.getLogger(ViewProfile.class.getName()).log(Level.SEVERE, null,ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProfileTable = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        back = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        set = new javax.swing.JLabel();
        txtPost = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        RecentTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Profiles");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 59, 49, 22));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 87, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 118, -1, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 61, 155, -1));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jLabel1.setText("Registered Profiles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 36, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel7.setText("Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 149, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 87, 155, -1));

        ProfileTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProfileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Type", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProfileTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProfileTable);
        if (ProfileTable.getColumnModel().getColumnCount() > 0) {
            ProfileTable.getColumnModel().getColumn(0).setResizable(false);
            ProfileTable.getColumnModel().getColumn(1).setResizable(false);
            ProfileTable.getColumnModel().getColumn(2).setResizable(false);
            ProfileTable.getColumnModel().getColumn(3).setResizable(false);
            ProfileTable.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 76, 530, 204));

        btnDelete.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        btnDelete.setText("1. Delete selected Item");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 320, -1, 24));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 118, 155, -1));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 281, 98, -1));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        btnUpdate.setText("2. Update selected Item");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        jLabel2.setText("Please choose in table to edit user profiles for:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 293, -1, 21));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jLabel3.setText("New User Registration");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, -1));

        logout.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 616, 176, 32));

        back.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 616, 176, 32));

        btnSubmit.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 281, -1, 23));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel9.setText("Contact");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 180, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 180, 155, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 266, 178, -1));
        getContentPane().add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 286, 130, 28));

        txtPost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Customer" }));
        txtPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPostActionPerformed(evt);
            }
        });
        getContentPane().add(txtPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 149, -1, -1));

        RecentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Gender", "Contact", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RecentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(RecentTable);
        if (RecentTable.getColumnModel().getColumnCount() > 0) {
            RecentTable.getColumnModel().getColumn(0).setResizable(false);
            RecentTable.getColumnModel().getColumn(1).setResizable(false);
            RecentTable.getColumnModel().getColumn(2).setResizable(false);
            RecentTable.getColumnModel().getColumn(3).setResizable(false);
            RecentTable.getColumnModel().getColumn(4).setResizable(false);
            RecentTable.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 447, 771, 151));

        jLabel10.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jLabel10.setText("Recent Request For Account Creation");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 406, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel11.setText("Username");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 211, -1, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel12.setText("Password");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 237, -1, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 211, 156, -1));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 237, 154, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/css/form/java pic/java1Background.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 0, 1210, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        setVisible(false);
        LoginPage log = new LoginPage();
        log.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        Admin a = new Admin();
        a.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
      
        set.setText("");
        ProfileDao ad = new ProfileDaoImpl();
        Profile a = new Profile();

        
        a.setId(txtId.getText());
        a.setName(txtName.getText());
        a.setAddress(txtAddress.getText());
        a.setPost(txtPost.getSelectedItem().toString());
        a.setEmail(txtEmail.getText());
            String d=user.getText();
           String b=pass.getText();
 
            // TODO add your handling code here:
          
        DefaultTableModel dtm =(DefaultTableModel)ProfileTable.getModel();
       
       if(!txtId.getText().trim().equals("") && !txtName.getText().trim().equals("") && !txtAddress.getText().trim().equals("") && !txtPost.getSelectedItem().toString().equals("")&& !txtEmail.getText().trim().equals("")){
          JOptionPane.showMessageDialog(null, "Account Creation Successfull.");
           try {
            ad.submitProfile(a);
            dtm.addRow(new Object[]{txtId.getText(),txtName.getText(), txtAddress.getText(), txtPost.getSelectedItem(),txtEmail.getText()});
              try (BufferedWriter bw = new BufferedWriter(new FileWriter("Users.txt", true))) {
                  bw.write(d + "," + b );
                  bw.flush();
                  bw.newLine();
              }
           } catch (IOException ex) {
            Logger.getLogger(AdminProfiles.class.getName()).log(Level.SEVERE, null, ex);
        } 
       }else{
        set.setText("Sorry! Please fill all the spaces. Thank You!!!!");
       } 

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        user.setText("");
        pass.setText("");
        txtId.setText("");
        txtName.setText("");     
        txtAddress.setText("");

        txtEmail.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProfileTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileTableMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) ProfileTable.getModel();
        int selectedRowIndex = ProfileTable.getSelectedRow();
        txtId.setText(dtm.getValueAt(selectedRowIndex, 0).toString());
        txtName.setText(dtm.getValueAt(selectedRowIndex, 1).toString());
        txtAddress.setText(dtm.getValueAt(selectedRowIndex, 2).toString());
        
        txtEmail.setText(dtm.getValueAt(selectedRowIndex, 4).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileTableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel model =(DefaultTableModel)ProfileTable.getModel();
           if(ProfileTable.getSelectedRow() == -1)
       {
           if(ProfileTable.getRowCount() == 0)
           {
               set.setText("Table is Empty");
           }else{
               set.setText("You must Select a Name of customer");
           }
       }else{
            try {
                model.removeRow(ProfileTable.getSelectedRow());
                ProfileDaoImpl p = new ProfileDaoImpl();
                p.deleteProfile(txtId.getText());
                p.deleteProfile(txtName.getText());
                p.deleteProfile(txtAddress.getText());
                p.deleteProfile(txtPost.getSelectedItem().toString());
                p.deleteProfile(txtEmail.getText());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Profile deleted succesfully");
                Logger.getLogger(AdminProfiles.class.getName()).log(Level.SEVERE, null, ex);
            }
       }         // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       
       DefaultTableModel tab =(DefaultTableModel)ProfileTable.getModel();
       if(ProfileTable.getSelectedRow() == -1)
       {
           if(ProfileTable.getRowCount() == 0)
           {
               set.setText("Table is Empty");
           }else{
               set.setText("You must Select a Manager");
           }
       }else{
           tab.setValueAt(txtId.getText(), ProfileTable.getSelectedRow(), 0);
           tab.setValueAt(txtName.getText(), ProfileTable.getSelectedRow(), 1);
           tab.setValueAt(txtAddress.getText(), ProfileTable.getSelectedRow(), 2);
           tab.setValueAt(txtPost.getSelectedItem().toString(), ProfileTable.getSelectedRow(), 3);
           tab.setValueAt(txtEmail.getText(), ProfileTable.getSelectedRow(), 4);
           
           
           Profile a = new Profile();
           a.Update(txtId.getText(),txtName.getText(),txtAddress.getText(), txtPost.getSelectedItem().toString(), txtEmail.getText());  
            JOptionPane.showMessageDialog(null, "Profile updated succesfully");        
       }       
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPostActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void RecentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecentTableMouseClicked


        
// TODO add your handling code here:
    }//GEN-LAST:event_RecentTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminProfiles().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProfileTable;
    private javax.swing.JTable RecentTable;
    private javax.swing.JButton back;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout;
    private javax.swing.JTextField pass;
    private javax.swing.JLabel set;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox txtPost;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables


 
}
